USE lab1; 
DROP TABLE IF EXISTS DEPT_LOCATION CASCADE;
DROP TABLE IF EXISTS WORKS_ON CASCADE;
DROP TABLE IF EXISTS DEPENDENT CASCADE;
DROP TABLE IF EXISTS PROJECT CASCADE;
SET foreign_key_checks = 0;
DROP TABLE IF EXISTS EMPLOYEE CASCADE;
SET foreign_key_checks = 1;
DROP TABLE IF EXISTS DEPARTMENT CASCADE;




DROP DATABASE IF EXISTS company;